definitions:
  dto.ApiResponseSuccessStruct:
    properties:
      data:
        example: "null"
        type: string
      message:
        example: Success
        type: string
    type: object
  dto.DoctorInfoRequest:
    properties:
      medical_license_number:
        type: string
      specialization:
        type: string
    required:
    - medical_license_number
    - specialization
    type: object
  dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.LogoutRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  dto.ManagerInfoRequest:
    properties:
      department:
        type: string
      status:
        type: string
    required:
    - department
    type: object
  dto.NurseInfoRequest:
    properties:
      nursing_license_number:
        type: string
    required:
    - nursing_license_number
    type: object
  dto.PatientInfoRequest:
    properties:
      allergies:
        type: string
      blood_type:
        type: string
      chronic_conditions:
        type: string
      insurance_number:
        type: string
      status:
        type: string
    type: object
  dto.RefreshRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  dto.RegisterRequest:
    properties:
      address:
        type: string
      citizen_id:
        type: string
      date_of_birth:
        type: string
      email:
        type: string
      gender:
        type: string
      manager_info:
        $ref: '#/definitions/dto.ManagerInfoRequest'
      name:
        type: string
      password:
        type: string
      patient_info:
        $ref: '#/definitions/dto.PatientInfoRequest'
      phone_number:
        type: string
      role:
        type: string
      staff_info:
        $ref: '#/definitions/dto.StaffInfoRequest'
    required:
    - address
    - citizen_id
    - date_of_birth
    - email
    - gender
    - name
    - password
    - phone_number
    - role
    type: object
  dto.StaffInfoRequest:
    properties:
      department:
        type: string
      doctor_info:
        $ref: '#/definitions/dto.DoctorInfoRequest'
      nurse_info:
        $ref: '#/definitions/dto.NurseInfoRequest'
      role:
        type: string
      status:
        type: string
    required:
    - department
    - role
    type: object
info:
  contact: {}
  description: Hospital Management API
  title: Hospital Management API
  version: "1.0"
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: User's email and password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ApiResponseSuccessStruct'
      summary: Login
      tags:
      - Auth
  /api/auth/logout:
    post:
      consumes:
      - application/json
      description: Logout
      parameters:
      - description: User's refresh token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LogoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ApiResponseSuccessStruct'
      summary: Logout
      tags:
      - Auth
  /api/auth/refresh:
    post:
      consumes:
      - application/json
      description: Refresh Access Token
      parameters:
      - description: User's refresh token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ApiResponseSuccessStruct'
      summary: Refresh Access Token
      tags:
      - Auth
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: Register new user
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      - description: Authorization
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ApiResponseSuccessStruct'
      security:
      - JWT: []
      summary: Register new user
      tags:
      - Auth
schemes:
- http
- https
swagger: "2.0"
