name: friends_management
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=${PORT}
      - APPLICATION_NAME=${APPLICATION_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - BASE_URL_BACKEND=${BASE_URL_BACKEND}
      - BASE_URL_BACKEND_FOR_SWAGGER=${BASE_URL_BACKEND_FOR_SWAGGER}
    depends_on:
      - postgres
    restart: on-failure
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: